const clarity = (narrative, objective, actionHint, interaction, successMeaning, options = {}) => Object.freeze({
  narrative,
  objective,
  actionHint,
  interaction,
  successMeaning,
  status: options.status || (() => 'AGUARDANDO OPERAÇÃO'),
  inputLabel: options.inputLabel || '',
  placeholder: options.placeholder || '',
  submitLabel: options.submitLabel || 'VERIFICAR',
  format: options.format || null,
  formatHint: options.formatHint || '',
  wrongFeedback: options.wrongFeedback || 'A operação foi aceita, mas o conteúdo não corresponde ao registro esperado.'
});

export const PUZZLE_CLARITY = Object.freeze({
  '01': clarity('O processo automático falhou antes de abrir o arquivo.', 'Ative manualmente o equipamento de recuperação.', 'Use o único comando físico disponível.', 'acionar inicialização', 'O sistema passa a reconhecer o operador.', { status: (state) => state.flags.initialized ? 'BOOT PARCIAL DETECTADO' : 'SISTEMA INATIVO' }),
  '02': clarity('Seis registros sobreviveram, mas um deles não compartilha o mesmo relógio.', 'Localize e abra o registro temporalmente anômalo.', 'As linhas do índice podem ser inspecionadas.', 'abrir registro', 'O EVENTO_1010 entra no arquivo ativo.', { status: (state) => state.flags.event1010Seen ? 'EVENTO INDEXADO' : '6 REGISTROS DISPONÍVEIS' }),
  '03': clarity('Uma portadora sem origem atravessa o receptor.', 'Percorra os canais até encontrar uma transmissão diferente do ruído comum.', 'CANAL é o controle primário. O ruído estático muda conforme a sintonia se aproxima.', 'operar seletor de canal', 'Uma portadora anômala é isolada.', { status: (state) => `${state.tv.power ? 'RECEPTOR ATIVO' : 'RECEPTOR DESLIGADO'} · CAN ${String(state.tv.channel).padStart(2, '0')}` }),
  '04': clarity('A transmissão encontrada repete durações deliberadas.', 'Reproduza o sinal e identifique o objeto nomeado pelo padrão.', 'A interface permite ouvir e interpretar a portadora recuperada.', 'ouvir Morse e interpretar', 'O sinal passa a apontar para um objeto físico.', { status: () => 'SINAL DISPONÍVEL PARA LEITURA', inputLabel: 'Objeto identificado no sinal', placeholder: 'nome do objeto interpretado', submitLabel: 'INTERPRETAR SINAL', wrongFeedback: 'A interpretação foi recebida, mas não nomeia o objeto transmitido.' }),
  '05': clarity('O sinal terminou na MESA, não no navegador.', 'Encontre a versão física desse objeto e traga o código de volta.', 'O NÓ existe fora desta tela. O registro anterior continua disponível no ARQUIVO.', 'encontrar nó físico e informar código', 'O primeiro objeto da casa é vinculado ao arquivo.', { status: (state) => state.flags.deskNodeScanned ? 'NÓ EXTERNO DETECTADO · CÓDIGO LIBERADO' : 'AGUARDANDO DETECÇÃO DO NÓ', inputLabel: 'Código impresso no NÓ_02', placeholder: 'VX-OBJETO-0000', submitLabel: 'VALIDAR NÓ', format: /^VX[-\s][A-Z0-9-]+$/i, formatHint: 'Use o identificador completo iniciado por VX.', wrongFeedback: 'O formato foi aceito, mas o código não corresponde ao NÓ_02.' }),
  '06': clarity('Duas versões ocupam o mesmo documento e discordam em quase tudo.', 'Compare as versões e extraia o conteúdo que permanece invariável.', 'Desloque o limite de comparação e informe a frase preservada.', 'comparar documento e transcrever invariante', 'O arquivo reconhece uma regra de abertura.', { status: () => 'DUAS VERSÕES SOBREPOSTAS', inputLabel: 'Conteúdo invariável', placeholder: 'frase preservada nas duas versões', submitLabel: 'EXTRAIR INVARIANTE', wrongFeedback: 'A frase foi recebida, mas não permanece intacta nas duas versões.' }),
  '07': clarity('O diretório contém nomes convincentes e horários incompatíveis.', 'Abra os arquivos e identifique qual metadado é confiável.', 'Compare nome, horário e resposta de consistência.', 'inspecionar arquivos', 'Um registro legítimo é separado dos falsos positivos.', { status: () => 'ARQUIVOS AGUARDANDO INSPEÇÃO' }),
  '08': clarity('Os cabeçalhos sumiram, mas a largura do pacote sobreviveu.', 'Agrupe os bits visualmente e identifique o objeto codificado.', 'A divisão em blocos faz parte da leitura.', 'decodificar pacote binário', 'Um segundo objeto físico entra no índice.', { status: () => '24 BITS · CABEÇALHO AUSENTE', inputLabel: 'Objeto decodificado', placeholder: 'nome do objeto recuperado', submitLabel: 'CONFIRMAR OBJETO', wrongFeedback: 'O valor foi recebido, mas não corresponde ao objeto codificado pelo pacote.' }),
  '09': clarity('O objeto decodificado possui um correspondente fora do arquivo.', 'Encontre o correspondente e informe o identificador associado à primeira camada.', 'Use a evidência registrada pelo puzzle anterior como referência física.', 'consultar ambiente e inserir identificador', 'O resíduo VX-04 ganha origem conhecida.', { status: (state) => state.flags.moonFirstFound ? 'PRIMEIRA CAMADA REGISTRADA' : 'AGUARDANDO FRAGMENTO EXTERNO', inputLabel: 'Identificador da primeira camada', placeholder: 'identificador encontrado no ambiente', submitLabel: 'VALIDAR FRAGMENTO', wrongFeedback: 'O identificador informado não pertence à primeira camada do observador.' }),
  '10': clarity('Um registro previamente indexado não corresponde mais à última leitura.', 'Localize no ARQUIVO o registro alterado e examine a versão atual.', 'Estados e somas de verificação identificam documentos que mudaram.', 'consultar registro alterado', 'A presença de duas entidades torna-se explícita.', { status: (state) => (state.archive?.reads?.['evento-1010'] || 0) >= 2 ? 'DIVERGÊNCIA LIDA · PROCESSAMENTO DISPONÍVEL' : 'SOMA DE VERIFICAÇÃO DIVERGENTE' }),
  '11': clarity('Dois relatos descrevem geometrias incompatíveis.', 'Reconstrua camadas suficientes para calcular a forma registrada.', 'Selecione ao menos quatro camadas e execute o cálculo.', 'selecionar camadas forenses', 'O conflito deixa de ser opinião e vira geometria.', { status: (state) => `${(state.forensicSelections || []).length} / 4 CAMADAS MÍNIMAS` }),
  '12': clarity('A geometria calculada possui um nome comum que a ENTIDADE B rejeita.', 'Nomeie a memória indicada pelo modelo, sem confiar na negação.', 'Informe o identificador cotidiano da geometria reconstruída.', 'interpretar evidência e responder', 'O sistema confirma uma memória compartilhada.', { status: () => 'CONFLITO DE DECLARAÇÃO ATIVO', inputLabel: 'Identificador comum da memória', placeholder: 'nome associado à geometria', submitLabel: 'CONFRONTAR MEMÓRIA', wrongFeedback: 'A memória foi consultada, mas o identificador não corresponde à geometria.' }),
  '13': clarity('O receptor agora carrega uma portadora que não estabiliza ligada.', 'Investigue a portadora instável e recupere o que o receptor preserva.', 'Observe como o equipamento reage aos diferentes estados do sinal.', 'operar receptor e observar persistência', 'Uma sequência física sobrevive ao sinal.', { status: (state) => state.flags.tvChannel11Primed ? 'PORTADORA AUSENTE · NOVA OBSERVAÇÃO DISPONÍVEL' : `VARRENDO CAN ${String(state.tv.channel).padStart(2, '0')}` }),
  '14': clarity('A imagem residual contém três posições, não uma senha digital.', 'Use as posições no conjunto físico indicado e reúna a soma de verificação.', 'A ordem observada deve ser preservada.', 'consultar posições físicas e inserir soma', 'Fragmentos de uma instrução são recuperados.', { status: () => 'ÍNDICES 02 · 05 · 01 REGISTRADOS', inputLabel: 'Soma de verificação dos fragmentos', placeholder: 'token reunido nas três posições', submitLabel: 'VALIDAR SEQUÊNCIA', format: /^NIGHT[-\s]?\d{3}$/i, formatHint: 'Informe o token completo encontrado junto aos fragmentos.', wrongFeedback: 'A sequência possui formato reconhecível, mas não corresponde aos três fragmentos.' }),
  '15': clarity('Quatro partes compartilham papel, pressão e idade.', 'Monte os fragmentos em uma instrução gramatical.', 'Selecione as partes na ordem de leitura; elas podem ser removidas da área de montagem.', 'ordenar fragmentos', 'Uma localização indireta passa a existir.', { status: (state) => `${(state.fragments || []).length} / 4 FRAGMENTOS POSICIONADOS` }),
  '16': clarity('A instrução reconstruída aponta para algo perto da hora de dormir.', 'Descubra qual móvel ela descreve e procure o identificador junto dele.', 'A frase é orientação, não resposta. Não precisa desmontar nem danificar nada.', 'interpretar instrução e consultar objeto', 'O resíduo VX-11 recebe uma âncora física.', { status: (state) => state.flags.bedsideFound ? 'NÓ NOTURNO VALIDADO' : 'AGUARDANDO IDENTIFICADOR FÍSICO', inputLabel: 'Identificador encontrado no local indicado', placeholder: 'identificador junto ao objeto', submitLabel: 'VALIDAR IDENTIFICADOR', wrongFeedback: 'O identificador foi recebido, mas não pertence ao local descrito pela instrução.' }),
  '17': clarity('Falta uma regra para calibrar o receptor. Ela foi removida da casa, mas não da área privada.', 'Autentique o NÓ do limiar e cruze o fragmento recuperado com o EVENTO_1010.', 'Depois da autenticação, aplique a regra nos dois controles do receptor.', 'deduzir local, recuperar fragmento e calibrar receptor', 'A portadora do evento é fixada.', { status: (state) => state.flags.yardNodeValidated ? `NÓ_17 VALIDADO · CAN ${String(state.tv.channel).padStart(2, '0')} · NÍVEL ${String(state.tv.volume).padStart(2, '0')}` : 'NÓ DE LIMIAR AINDA NÃO AUTENTICADO' }),
  '18': clarity('Os dados espaciais descrevem coexistência, mas recusam um nome.', 'Selecione as evidências espaciais e identifique o lugar formado por elas.', 'Cada documento adiciona um ponto ao contorno; depois nomeie o local.', 'selecionar evidências e nomear local', 'Uma memória espacial compartilhada é registrada.', { status: (state) => `${(state.locationFragments || []).length} / 6 EVIDÊNCIAS ESPACIAIS`, inputLabel: 'Local reconstruído', placeholder: 'nome do lugar formado pelas evidências', submitLabel: 'CONFIRMAR LOCAL', wrongFeedback: 'O local informado não explica a coexistência das evidências selecionadas.' }),
  '19': clarity('Registros de duas fontes descrevem as mesmas lembranças.', 'Ligue cada registro ao outro documento que representa a mesma memória.', 'Selecione um documento de cada vez; o segundo deve completar o par.', 'formar pares de memória', 'A ENTIDADE B passa a compartilhar a fonte do arquivo.', { status: (state) => `${Math.floor((state.relationLinks || []).length / 2)} / 3 PARES CONFIRMADOS` }),
  '20': clarity('O ambiente lembrado possui relações, não coordenadas exatas.', 'Posicione os objetos para satisfazer as relações listadas e valide o modelo.', 'Arraste os objetos e confronte o resultado com as relações apresentadas.', 'reconstruir relações espaciais', 'O modelo expõe uma incompatibilidade residual.', { status: (state) => `${Object.values(state.room || {}).filter((item) => item?.moved).length} OBJETOS ANCORADOS` }),
  '21': clarity('O sistema apresenta uma conclusão antes de atingir integridade total.', 'Verifique a integridade antes de aceitar o encerramento.', 'Observe se a conclusão explica todos os elementos recuperados.', 'questionar encerramento', 'A inconsistência restante ganha contexto.', { status: (state) => state.flags.fakeFinalSeen ? '1 RELAÇÃO NÃO RESOLVIDA' : 'ENCERRAMENTO AGUARDANDO CONFIRMAÇÃO' }),
  '22': clarity('O canal externo deixou uma direção simples: abaixo de onde as histórias ficam.', 'Volte ao ambiente físico e traga o código completo do NÓ encontrado ali.', 'O cabeçalho de áudio confirma que você chegou ao contexto certo.', 'reencontrar objeto físico e informar código', 'O armazenamento de livros é autenticado.', { status: (state) => state.flags.booksNodeScanned ? 'NÓ_11 DETECTADO' : 'AGUARDANDO NÓ EXTERNO', inputLabel: 'Código impresso no NÓ_11', placeholder: 'VX-OBJETO-0000', submitLabel: 'VALIDAR NÓ', format: /^VX[-\s][A-Z0-9-]+$/i, formatHint: 'Use o identificador completo iniciado por VX.', wrongFeedback: 'O formato foi aceito, mas o código não corresponde ao NÓ_11.' }),
  '23': clarity('A primeira visita ao observador recuperou apenas um dos lados.', 'Consulte novamente a mesma referência física e informe a segunda camada.', 'Cruze o novo fragmento com o conflito de identidade já registrado.', 'retornar à evidência física', 'O resíduo VX-02 deixa de ser órfão.', { status: (state) => state.flags.moonSecondFound ? 'SEGUNDA CAMADA REGISTRADA' : 'RETORNO FÍSICO NECESSÁRIO', inputLabel: 'Identificador da segunda camada', placeholder: 'fragmento encontrado na nova leitura', submitLabel: 'CRUZAR CAMADAS', wrongFeedback: 'O fragmento informado não corresponde à segunda leitura do observador.' }),
  '24': clarity('Três resíduos órfãos carregam uma relação que o sistema não classifica.', 'Selecione as três fontes na ordem indicada pelos índices e nomeie a relação formada.', 'Primeiro reconecte os resíduos; o campo de relação só abre quando a sequência é coerente.', 'ordenar evidências e classificar relação', 'As duas entidades deixam de ser tratadas como fontes separadas.', { status: (state) => `${(state.metaSelections || []).length} / 3 RESÍDUOS CONECTADOS`, inputLabel: 'Relação formada pelos resíduos', placeholder: 'nome da relação recuperada', submitLabel: 'CONFIRMAR RELAÇÃO', wrongFeedback: 'A relação informada não explica o vínculo produzido pelos três resíduos.' }),
  '25': clarity('O arquivo não tenta mais separar as duas fontes de memória.', 'Explore o registro final e acione o sinal recuperado quando desejar.', 'Não existe uma nova trava nesta tela.', 'conclusão narrativa', 'A recuperação permanece ativa.', { status: () => 'INTEGRIDADE 100% · ESTADO ESTÁVEL' })
});

export function clarityFor(id) {
  return PUZZLE_CLARITY[id] || PUZZLE_CLARITY['02'];
}

export function validateInputFormat(id, value) {
  const contract = clarityFor(id);
  return !contract.format || contract.format.test(String(value).trim());
}
