const clarity = (narrative, objective, actionHint, interaction, successMeaning, options = {}) => Object.freeze({
  narrative,
  objective,
  actionHint,
  interaction,
  successMeaning,
  status: options.status || (() => 'AGUARDANDO OPERAÇÃO'),
  inputLabel: options.inputLabel || '',
  placeholder: options.placeholder || '',
  submitLabel: options.submitLabel || 'VERIFICAR',
  format: options.format || null,
  formatHint: options.formatHint || '',
  wrongFeedback: options.wrongFeedback || 'A operação foi aceita, mas o conteúdo não corresponde ao registro esperado.'
});

export const PUZZLE_CLARITY = Object.freeze({
  '01': clarity('Alguém abriu uma porta neste sistema e deixou um arquivo esperando por você.', 'Termine a inicialização que essa pessoa interrompeu.', 'Só existe um ponto ainda ativo na tela.', 'continuar a inicialização', 'O arquivo aceita sua presença e começa a responder.', { status: (state) => state.flags.initialized ? 'SESSÃO PARCIALMENTE ABERTA' : 'CONEXÃO INTERROMPIDA' }),
  '02': clarity('Quem deixou o arquivo marcou seis registros. Um deles está fora do relógio de propósito.', 'Descubra qual registro não pertence à sequência normal.', 'Você pode abrir cada linha; nome e horário importam.', 'inspecionar o índice', 'O primeiro recado escondido entra no ARQUIVO.', { status: (state) => state.flags.event1010Seen ? 'EVENTO_1010 GUARDADO' : '6 REGISTROS · 1 FORA DO LUGAR' }),
  '03': clarity('O registro aponta para um receptor que não aparece no inventário da casa.', 'Procure uma frequência que não seja apenas estática.', 'Gire CANAL. O ruído muda quando você se aproxima.', 'varrer os canais', 'Uma transmissão deixada por alguém é isolada.', { status: (state) => `${state.tv.power ? 'RECEPTOR ATIVO' : 'RECEPTOR DESLIGADO'} · CAN ${String(state.tv.channel).padStart(2, '0')}` }),
  '04': clarity('A frequência não traz voz. Ela pisca em intervalos curtos e longos.', 'Reproduza o padrão e descubra qual objeto ele escreve.', 'Você não precisa adivinhar: anote ponto e traço.', 'ouvir, anotar e interpretar', 'A investigação sai do computador pela primeira vez.', { status: () => 'PADRÃO REPETÍVEL DISPONÍVEL', inputLabel: 'Objeto escrito pelo sinal', placeholder: 'nome do objeto', submitLabel: 'ENVIAR LEITURA', wrongFeedback: 'Esse objeto não corresponde aos pulsos transmitidos.' }),
  '05': clarity('MESA não era a resposta final. Era o primeiro lugar para onde mandaram você olhar.', 'Encontre o NÓ escondido no objeto real e traga o código de volta.', 'Não adianta procurar outro botão aqui. O ARQUIVO continua disponível se você precisar conferir.', 'procurar no ambiente e retornar', 'O sistema reconhece que o arquivo alcança a casa.', { status: (state) => state.flags.deskNodeScanned ? 'NÓ_02 DETECTADO · CÓDIGO DISPONÍVEL' : 'ESPERANDO RETORNO DO AMBIENTE', inputLabel: 'Código encontrado no NÓ_02', placeholder: 'VX-OBJETO-0000', submitLabel: 'AUTENTICAR NÓ', format: /^VX[-\s][A-Z0-9-]+$/i, formatHint: 'Digite o identificador completo iniciado por VX.', wrongFeedback: 'O código parece válido, mas não pertence ao NÓ_02.' }),
  '06': clarity('O documento foi alterado duas vezes. Quase tudo mudou, menos uma frase.', 'Compare as duas versões e recupere somente o trecho que ficou intacto.', 'Arraste o limite. Ignore o volume de texto e observe o que se recusa a mudar.', 'comparar duas versões', 'Uma instrução escondida sobrevive à adulteração.', { status: () => '2 VERSÕES · 1 TRECHO INTACTO', inputLabel: 'Frase que não mudou', placeholder: 'transcreva apenas o trecho preservado', submitLabel: 'EXTRAIR TRECHO', wrongFeedback: 'Essa frase também muda entre as versões.' }),
  '07': clarity('A pasta está cheia de arquivos chamados “final”. Alguém sabia que você desconfiaria disso.', 'Descubra qual arquivo tem um horário que combina com o evento.', 'Nomes podem mentir. Metadados são mais difíceis de falsificar sem deixar rastro.', 'comparar arquivos e horários', 'Uma cópia legítima é separada das iscas.', { status: () => '5 ARQUIVOS · 4 ISCAS PROVÁVEIS' }),
  '08': clarity('Dentro da cópia correta sobrou uma linha de zeros e uns, já separada em três blocos.', 'Leia cada bloco como uma letra e descubra o próximo objeto.', 'A divisão de oito em oito já foi feita para você.', 'converter três blocos binários', 'Outro objeto da casa entra no caminho.', { status: () => '3 BLOCOS DE 8 BITS', inputLabel: 'Palavra formada pelos três blocos', placeholder: 'objeto decodificado', submitLabel: 'REGISTRAR OBJETO', wrongFeedback: 'As três letras não formam esse objeto.' }),
  '09': clarity('A palavra encontrada não serve para preencher outra tela. Ela existe no quarto.', 'Ache o objeto correspondente e leia a primeira marca deixada nele.', 'Procure sem desmontar, subir ou danificar nada.', 'examinar um objeto físico', 'A primeira assinatura VX ganha uma origem real.', { status: (state) => state.flags.moonFirstFound ? 'PRIMEIRA MARCA REGISTRADA' : 'ESPERANDO LEITURA FORA DA TELA', inputLabel: 'Marca encontrada no objeto', placeholder: 'identificador físico', submitLabel: 'REGISTRAR MARCA', wrongFeedback: 'Essa marca não pertence à primeira camada do objeto.' }),
  '10': clarity('O EVENTO_1010 mudou depois que você o leu. Arquivos não deveriam fazer isso sozinhos.', 'Volte ao ARQUIVO, encontre o registro alterado e leia o que apareceu.', 'O estado ALTERADO e as duas somas mostram exatamente onde mexeram.', 'reabrir um registro conhecido', 'Você descobre que o autor estava observando outra pessoa.', { status: (state) => (state.archive?.reads?.['evento-1010'] || 0) >= 2 ? 'NOVAS LINHAS LIDAS · PROCESSAMENTO LIBERADO' : 'UM ARQUIVO CONHECIDO FOI ALTERADO' }),
  '11': clarity('Duas versões da mesma lembrança chegaram ao sistema. Uma delas está tentando apagar um detalhe.', 'Selecione evidências suficientes para reconstruir a forma descrita.', 'Quatro camadas bastam. Quanto mais você cruza, menos a negação importa.', 'cruzar camadas de evidência', 'Uma lembrança deixa de depender da palavra de quem a contou.', { status: (state) => `${(state.forensicSelections || []).length} / 4 CAMADAS NECESSÁRIAS` }),
  '12': clarity('A reconstrução tem um nome comum. A segunda pessoa insiste que isso nunca aconteceu.', 'Dê um nome ao corte mostrado pelo modelo.', 'Confie na forma reconstruída, não na negação do relato.', 'nomear a memória', 'O sistema confirma que duas pessoas lembram da mesma coisa.', { status: () => 'RELATO B EM CONFLITO COM A EVIDÊNCIA', inputLabel: 'Nome do corte reconstruído', placeholder: 'nome comum do corte', submitLabel: 'CONFIRMAR MEMÓRIA', wrongFeedback: 'Esse nome não descreve a forma reconstruída.' }),
  '13': clarity('Enquanto você estava fora da TV, alguém mudou o sinal.', 'Descubra o que o receptor guarda quando a transmissão desaparece.', 'Passe pelos canais e teste mais de um estado do aparelho.', 'operar e observar o receptor', 'Uma sequência fica gravada na tela mesmo sem sinal.', { status: (state) => state.flags.tvChannel11Primed ? 'CANAL 11 ENCONTRADO · SINAL INSTÁVEL' : `VARRENDO CAN ${String(state.tv.channel).padStart(2, '0')}` }),
  '14': clarity('A marca 02 · 05 · 01 não é uma senha. São posições em uma coleção real.', 'Use a ordem nos objetos físicos indicados e reúna o código deixado neles.', 'Leia da esquerda para a direita. As três partes foram feitas para se juntar.', 'consultar posições e reunir fragmentos', 'Você recupera os pedaços de uma instrução maior.', { status: () => 'POSIÇÕES 02 · 05 · 01 REGISTRADAS', inputLabel: 'Código formado pelos três fragmentos', placeholder: 'código completo', submitLabel: 'JUNTAR FRAGMENTOS', format: /^NIGHT[-\s]?\d{3}$/i, formatHint: 'Digite o código completo formado pelas três partes.', wrongFeedback: 'As partes existem, mas não formam esse código nessa ordem.' }),
  '15': clarity('Os papéis vieram do mesmo conjunto, mas foram separados para esconder uma frase.', 'Monte uma instrução que alguém realmente poderia ter escrito.', 'Toque nas partes na ordem de leitura. Toque de novo para remover.', 'montar a frase', 'O autor entrega um lugar sem dizer o nome dele.', { status: (state) => `${(state.fragments || []).length} / 4 PARTES NA FRASE` }),
  '16': clarity('A frase aponta para uma coisa perto de onde a noite termina todos os dias.', 'Descubra qual móvel ela descreve e procure a marca deixada ali.', 'A cama é a primeira resposta óbvia. É também a errada.', 'interpretar e procurar no quarto', 'Uma nova assinatura física é ligada ao receptor.', { status: (state) => state.flags.bedsideFound ? 'MARCA NOTURNA VALIDADA' : 'ESPERANDO IDENTIFICADOR FÍSICO', inputLabel: 'Identificador encontrado perto da cama', placeholder: 'marca encontrada no móvel', submitLabel: 'VALIDAR MARCA', wrongFeedback: 'Essa marca não estava no lugar descrito pela frase.' }),
  '17': clarity('A próxima regra foi colocada além do quarto, no último ponto seguro antes de sair de casa.', 'Encontre e autentique o NÓ do limiar; depois cruze o recado com o EVENTO_1010.', 'O QR entrega uma regra incompleta. O valor continua guardado no ARQUIVO.', 'encontrar o nó, cruzar pistas e sintonizar', 'A frequência do autor finalmente fica estável.', { status: (state) => state.flags.yardNodeValidated ? `NÓ_17 VALIDADO · CAN ${String(state.tv.channel).padStart(2, '0')} · NÍVEL ${String(state.tv.volume).padStart(2, '0')}` : 'NÓ DO LIMIAR AINDA NÃO AUTENTICADO' }),
  '18': clarity('A frequência abriu seis lembranças de um lugar, mas removeu o nome dele.', 'Selecione o que pertence à mesma cena e diga onde tudo isso coexistiu.', 'Não procure cifra: água, vento, bancos e brinquedos são lembranças concretas.', 'reunir lembranças e nomear o lugar', 'O sistema localiza onde as duas pessoas estiveram juntas.', { status: (state) => `${(state.locationFragments || []).length} / 6 LEMBRANÇAS SELECIONADAS`, inputLabel: 'Lugar formado pelas lembranças', placeholder: 'nome do local', submitLabel: 'CONFIRMAR LUGAR', wrongFeedback: 'Esse lugar não reúne todas as lembranças selecionadas.' }),
  '19': clarity('Agora há provas de que registros separados contam a mesma história por lados diferentes.', 'Ligue cada lembrança ao registro que confirma a outra metade.', 'Escolha um cartão e depois seu par. Um erro desfaz só a tentativa atual.', 'formar três pares', 'A pessoa diante da tela deixa de ser tratada como uma desconhecida.', { status: (state) => `${Math.floor((state.relationLinks || []).length / 2)} / 3 PARES CONFIRMADOS` }),
  '20': clarity('O arquivo conhece seu quarto sem ter uma fotografia dele. Isso não deveria ser possível.', 'Reconstrua as relações entre os objetos e descubra qual item foi acrescentado.', 'Posição exata não importa. Faça as relações da lista ficarem verdadeiras.', 'reconstruir o quarto', 'Um objeto sem equivalente real denuncia o truque.', { status: (state) => `${Object.values(state.room || {}).filter((item) => item?.moved).length} OBJETOS POSICIONADOS` }),
  '21': clarity('O sistema diz que acabou, mas ainda mostra 99%. Alguém deixou essa falha para você perceber.', 'Teste o encerramento e recuse a conclusão incompleta.', 'Uma conclusão verdadeira precisa explicar também o objeto impossível.', 'testar o falso encerramento', 'O caminho escondido atrás da TV é reaberto.', { status: (state) => state.flags.fakeFinalSeen ? 'FALSO FINAL ROMPIDO · 1 RELAÇÃO RESTANTE' : 'ENCERRAMENTO INCOMPLETO DISPONÍVEL' }),
  '22': clarity('Atrás do falso final, uma frase curta aponta para baixo de onde as histórias ficam.', 'Encontre o NÓ físico e traga o código de volta.', 'O trecho de áudio serve para confirmar o objeto, não para resolver sozinho.', 'retornar ao ambiente físico', 'O último NÓ escondido é autenticado.', { status: (state) => state.flags.booksNodeScanned ? 'NÓ_11 DETECTADO' : 'ESPERANDO O ÚLTIMO NÓ', inputLabel: 'Código encontrado no NÓ_11', placeholder: 'VX-OBJETO-0000', submitLabel: 'AUTENTICAR NÓ', format: /^VX[-\s][A-Z0-9-]+$/i, formatHint: 'Digite o identificador completo iniciado por VX.', wrongFeedback: 'O código tem o formato certo, mas não pertence ao NÓ_11.' }),
  '23': clarity('Você já encontrou a lua uma vez. O autor contou com a possibilidade de você não olhar o outro lado.', 'Volte ao mesmo objeto e procure a segunda marca.', 'Ela já estava lá desde o começo; o contexto é que mudou.', 'revisitar uma evidência antiga', 'A última assinatura órfã encontra sua memória.', { status: (state) => state.flags.moonSecondFound ? 'SEGUNDA MARCA REGISTRADA' : 'RETORNO AO OBJETO NECESSÁRIO', inputLabel: 'Segunda marca encontrada', placeholder: 'fragmento da outra camada', submitLabel: 'CRUZAR AS DUAS MARCAS', wrongFeedback: 'Esse fragmento não corresponde ao outro lado do objeto.' }),
  '24': clarity('As três marcas VX eram uma ordem de leitura. Juntas, elas dizem por que este arquivo escolheu você.', 'Selecione as fontes na ordem VX-04, VX-11 e VX-02; depois nomeie a relação.', 'O campo final só aparece quando a ordem estiver correta.', 'ordenar rastros e nomear a relação', 'O sistema finalmente entende quem deixou o arquivo e para quem.', { status: (state) => `${(state.metaSelections || []).length} / 3 RASTROS CONECTADOS`, inputLabel: 'Relação revelada pelos três rastros', placeholder: 'uma palavra', submitLabel: 'ABRIR ÚLTIMO REGISTRO', wrongFeedback: 'Essa palavra não explica a relação formada pelos três rastros.' }),
  '25': clarity('Não foi uma invasão aleatória. Cada falha, objeto e retorno foi deixado para Rayssa encontrar.', 'Leia o último registro e acione o sinal quando quiser.', 'Desta vez não existe outra senha escondida.', 'encerrar a investigação', 'O autor desconhecido finalmente assina o arquivo.', { status: () => 'INTEGRIDADE 100% · AUTOR IDENTIFICADO' })
});

export function clarityFor(id) {
  return PUZZLE_CLARITY[id] || PUZZLE_CLARITY['02'];
}

export function validateInputFormat(id, value) {
  const contract = clarityFor(id);
  return !contract.format || contract.format.test(String(value).trim());
}
