const contract = (act, area, motion, corruption, receiverImpact, options = {}) => Object.freeze({
  act,
  area,
  motion,
  corruption,
  receiverImpact,
  mutatesSystem: Boolean(options.mutatesSystem),
  retroactive: Boolean(options.retroactive),
  requirements: options.requirements || [],
  evidence: options.evidence || []
});

export const PUZZLE_CONTRACTS = Object.freeze({
  '01': contract(1, 'archive', 'signature', 0, 1, { mutatesSystem: true, evidence: ['evento-1010'] }),
  '02': contract(1, 'archive', 'low', 0, 1, { retroactive: true, requirements: ['01'], evidence: ['evento-1010','vx-04','vx-11','vx-02'] }),
  '03': contract(1, 'receiver', 'signature', 1, 3, { mutatesSystem: true, retroactive: true, requirements: ['02'], evidence: ['receiver-04'] }),
  '04': contract(1, 'receiver', 'high', 1, 3, { requirements: ['03'], evidence: ['object-desk'] }),
  '05': contract(1, 'cold-storage', 'high', 1, 1, { mutatesSystem: true, retroactive: true, requirements: ['04'], evidence: ['node-02'] }),
  '06': contract(2, 'archive', 'signature', 1, 0, { mutatesSystem: true, requirements: ['05'], evidence: ['document-invariant'] }),
  '07': contract(2, 'archive', 'high', 2, 1, { mutatesSystem: true, requirements: ['06'], evidence: ['file-1010'] }),
  '08': contract(2, 'archive', 'medium', 1, 0, { requirements: ['07'], evidence: ['object-moon'] }),
  '09': contract(2, 'cold-storage', 'high', 2, 1, { mutatesSystem: true, retroactive: true, requirements: ['08'], evidence: ['vx-04-moon'] }),
  '10': contract(2, 'archive', 'high', 3, 1, { mutatesSystem: true, retroactive: true, requirements: ['09','02'], evidence: ['shared-event'] }),
  '11': contract(3, 'evidence', 'signature', 2, 1, { mutatesSystem: true, requirements: ['10'], evidence: ['hair-geometry','entity-b-denial'] }),
  '12': contract(3, 'identity', 'high', 2, 1, { mutatesSystem: true, retroactive: true, requirements: ['11'], evidence: ['memory-mullet'] }),
  '13': contract(3, 'receiver', 'signature', 3, 3, { mutatesSystem: true, retroactive: true, requirements: ['12','03'], evidence: ['receiver-afterimage'] }),
  '14': contract(3, 'cold-storage', 'medium', 2, 2, { retroactive: true, requirements: ['13'], evidence: ['book-fragments'] }),
  '15': contract(3, 'evidence', 'medium', 2, 1, { mutatesSystem: true, requirements: ['14'], evidence: ['night-instruction'] }),
  '16': contract(3, 'cold-storage', 'medium', 2, 2, { mutatesSystem: true, retroactive: true, requirements: ['15'], evidence: ['vx-11-receiver'] }),
  '17': contract(3, 'receiver', 'signature', 3, 3, { mutatesSystem: true, retroactive: true, requirements: ['16','evento-1010'], evidence: ['node-17','calibration-fragment','carrier-1010'] }),
  '18': contract(4, 'evidence', 'signature', 3, 1, { mutatesSystem: true, requirements: ['17'], evidence: ['location-park'] }),
  '19': contract(4, 'identity', 'high', 4, 1, { mutatesSystem: true, retroactive: true, requirements: ['18','12','10'], evidence: ['shared-memory'] }),
  '20': contract(4, 'cold-storage', 'signature', 4, 2, { mutatesSystem: true, requirements: ['19'], evidence: ['room-match','impossible-tv'] }),
  '21': contract(4, 'receiver', 'signature', 4, 3, { mutatesSystem: true, retroactive: true, requirements: ['20'], evidence: ['system-object-tv'] }),
  '22': contract(4, 'cold-storage', 'medium', 4, 2, { mutatesSystem: true, retroactive: true, requirements: ['21'], evidence: ['node-11','audio-header'] }),
  '23': contract(4, 'identity', 'high', 4, 2, { mutatesSystem: true, retroactive: true, requirements: ['22','09'], evidence: ['vx-02-conflict'] }),
  '24': contract(5, 'identity', 'signature', 5, 3, { mutatesSystem: true, retroactive: true, requirements: ['23'], evidence: ['relation-us'] }),
  '25': contract(5, 'identity', 'signature', 0, 1, { mutatesSystem: true, requirements: ['24'] })
});

export const PUZZLE_SOLUTIONS = Object.freeze({
  '01': 'acionar o cursor do comando interrompido',
  '02': 'abrir EVENTO_1010',
  '03': 'sintonizar o canal 04',
  '04': 'MESA',
  '05': 'VX-MESA-1010',
  '06': 'A DATA ABRE O ARQUIVO',
  '07': 'final_agora_vai.txt',
  '08': 'LUA',
  '09': 'VX-04',
  '10': 'localizar no ARQUIVO o registro com checksum alterado',
  '11': 'reconstruir ao menos quatro camadas forenses',
  '12': 'MULLET',
  '13': 'canal 11 e desligamento para revelar a imagem residual',
  '14': 'NIGHT-251',
  '15': 'ONDE A NOITE DEIXA O QUE VOCÊ PRECISA',
  '16': 'VX-11',
  '17': 'autenticar NÓ_17, cruzar “repita o evento” com EVENTO_1010 e ajustar canal 10 + volume 10',
  '18': 'PARQUINHO DA BEIRA-MAR',
  '19': 'ligar os três pares de memórias',
  '20': 'estabelecer ao menos quatro relações espaciais válidas',
  '21': 'encerrar o falso final e retornar ao arquivo',
  '22': 'VX-LIVROS-0214',
  '23': 'VX-02',
  '24': 'LUA → TV → MULLET → NÓS',
  '25': 'conclusão narrativa sem nova trava'
});
