export const AUDIO_BUSES = Object.freeze({
  ambience: .34,
  device: .5,
  ui: .42,
  signal: .48,
  narrative: .56,
  impact: .62
});

export const AUDIO_MANIFEST = Object.freeze({
  'ui.contact': { generator: 'click', bus: 'ui', volume: .18, duration: .035, variants: [{ frequency: 760 }, { frequency: 690 }, { frequency: 820 }] },
  'ui.reject': { generator: 'tone', bus: 'ui', volume: .13, duration: .09, frequency: 118, type: 'square', filter: 620 },
  'input.invalid': { generator: 'click', bus: 'ui', volume: .1, duration: .04, variants: [{ frequency: 330 }, { frequency: 295 }] },
  'input.wrong': { generator: 'tone', bus: 'ui', volume: .13, duration: .14, frequency: 104, endFrequency: 78, type: 'triangle', filter: 380 },
  'system.error': { generator: 'impact', bus: 'impact', volume: .16, duration: .24, frequency: 62, endFrequency: 41 },
  'ui.accept': { generator: 'relay', bus: 'ui', volume: .18, duration: .16, variants: [{ frequency: 430 }, { frequency: 470 }] },
  'system.relay': { generator: 'relay', bus: 'device', volume: .28, duration: .13, variants: [{ frequency: 170 }, { frequency: 195 }, { frequency: 152 }] },
  'system.disk': { generator: 'disk', bus: 'device', volume: .12, duration: .24, variants: [{ frequency: 930 }, { frequency: 1080 }] },
  'computer.window.open': { generator: 'relay', bus: 'ui', volume: .08, duration: .075, frequency: 260 },
  'computer.window.close': { generator: 'click', bus: 'ui', volume: .07, duration: .045, frequency: 190 },
  'computer.window.minimize': { generator: 'tone', bus: 'ui', volume: .045, duration: .065, frequency: 310, endFrequency: 190, type: 'triangle' },
  'computer.window.maximize': { generator: 'tone', bus: 'ui', volume: .05, duration: .075, frequency: 190, endFrequency: 320, type: 'triangle' },
  'computer.folder.open': { generator: 'disk', bus: 'device', volume: .07, duration: .16, frequency: 860 },
  'computer.clock.apply': { generator: 'relay', bus: 'device', volume: .14, duration: .18, frequency: 205 },
  'computer.file.changed': { generator: 'disk', bus: 'narrative', volume: .09, duration: .42, frequency: 720, endFrequency: 940 },
  'phone.lock': { generator: 'click', bus: 'device', volume: .11, duration: .045, frequency: 520 },
  'phone.unlock': { generator: 'tone', bus: 'device', volume: .09, duration: .1, frequency: 620, endFrequency: 820, type: 'sine' },
  'phone.tap': { generator: 'click', bus: 'ui', volume: .055, duration: .025, frequency: 690 },
  'phone.message': { generator: 'tone', bus: 'device', volume: .12, duration: .18, frequency: 880, endFrequency: 660, type: 'triangle' },
  'phone.incoming': { generator: 'tone', bus: 'device', volume: .09, duration: .42, frequency: 520, endFrequency: 610, type: 'triangle' },
  'phone.vibration': { generator: 'noise', bus: 'device', volume: .08, duration: .24, filterType: 'lowpass', filter: 180, q: 1.2 },
  'source.03': { generator: 'impact', bus: 'signal', volume: .11, duration: .7, frequency: 72, endFrequency: 48 },
  'source.signature': { generator: 'impact', bus: 'narrative', volume: .085, duration: .12, frequency: 84, endFrequency: 62 },
  'system.flyback': { generator: 'tone', bus: 'device', volume: .035, duration: .62, frequency: 10800, endFrequency: 12600, type: 'sine' },
  'receiver.knob': { generator: 'click', bus: 'device', volume: .24, duration: .045, variants: [{ frequency: 372 }, { frequency: 410 }, { frequency: 438 }, { frequency: 465 }, { frequency: 492 }], rateVariation: .025 },
  'receiver.volume': { generator: 'click', bus: 'device', volume: .12, duration: .03, variants: [{ frequency: 590 }, { frequency: 625 }, { frequency: 660 }, { frequency: 695 }] },
  'receiver.power': { generator: 'relay', bus: 'device', volume: .36, duration: .18, variants: [{ frequency: 112 }, { frequency: 126 }] },
  'receiver.static': { generator: 'noise', bus: 'signal', volume: .25, duration: .16, filterType: 'bandpass', filter: 1750, q: .62, variants: [{ filter: 1320, q: .5 }, { filter: 1750, q: .62 }, { filter: 2240, q: .82 }, { filter: 860, q: 1.1 }], panVariation: .12 },
  'receiver.interference': { generator: 'noise', bus: 'signal', volume: .2, duration: .32, filterType: 'bandpass', filter: 780, q: 1.8 },
  'receiver.lock': { generator: 'tone', bus: 'signal', volume: .14, duration: .24, frequency: 740, endFrequency: 510, type: 'sine', filter: 1800 },
  'receiver.collapse': { generator: 'tone', bus: 'device', volume: .22, duration: .45, frequency: 180, endFrequency: 38, type: 'sawtooth', filter: 520 },
  'forensic.contact': { generator: 'click', bus: 'ui', volume: .09, duration: .028, variants: [{ frequency: 520 }, { frequency: 570 }] },
  'forensic.resolve': { generator: 'tone', bus: 'narrative', volume: .12, duration: .34, frequency: 86, endFrequency: 124, type: 'sine', filter: 420 },
  'evidence.trace': { generator: 'noise', bus: 'ui', volume: .035, duration: .13, filterType: 'bandpass', filter: 1180, q: 2.2, panVariation: .08 },
  'evidence.link': { generator: 'impact', bus: 'narrative', volume: .09, duration: .16, frequency: 92, endFrequency: 74 },
  'evidence.reject': { generator: 'click', bus: 'ui', volume: .08, duration: .055, frequency: 240 },
  'archive.seek': { generator: 'disk', bus: 'device', volume: .09, duration: .3, variants: [{ frequency: 820 }, { frequency: 980 }, { frequency: 1140 }] },
  'archive.engage': { generator: 'relay', bus: 'device', volume: .12, duration: .12, variants: [{ frequency: 144 }, { frequency: 168 }] },
  'archive.data': { generator: 'noise', bus: 'device', volume: .045, duration: .11, filterType: 'bandpass', filter: 1420, q: 2.4 },
  'archive.close': { generator: 'relay', bus: 'device', volume: .08, duration: .1, frequency: 118 },
  'archive.fault': { generator: 'noise', bus: 'signal', volume: .065, duration: .075, filterType: 'highpass', filter: 1880, q: 1.4 },
  'paper.lift': { generator: 'noise', bus: 'ui', volume: .05, duration: .08, filterType: 'bandpass', filter: 1850, q: .55, variants: [{ filter: 1550 }, { filter: 2050 }, { filter: 2380 }] },
  'paper.place': { generator: 'noise', bus: 'ui', volume: .07, duration: .1, filterType: 'lowpass', filter: 820, q: .45, variants: [{ filter: 690 }, { filter: 840 }, { filter: 960 }] },
  'paper.slide': { generator: 'noise', bus: 'ui', volume: .045, duration: .13, filterType: 'bandpass', filter: 1240, q: .7 },
  'object.contact': { generator: 'click', bus: 'ui', volume: .08, duration: .035, variants: [{ frequency: 290 }, { frequency: 340 }, { frequency: 410 }], rateVariation: .025 },
  'object.drop': { generator: 'impact', bus: 'ui', volume: .1, duration: .12, frequency: 94, endFrequency: 68 },
  'object.lock': { generator: 'relay', bus: 'device', volume: .08, duration: .1, frequency: 210 },
  'structure.confirm': { generator: 'impact', bus: 'narrative', volume: .09, duration: .25, frequency: 54, endFrequency: 42 },
  'reconstruction.process': { generator: 'disk', bus: 'device', volume: .07, duration: .22, variants: [{ frequency: 660 }, { frequency: 740 }] },
  'memory.resolve': { generator: 'tone', bus: 'narrative', volume: .11, duration: .48, frequency: 132, endFrequency: 196, type: 'triangle', filter: 560 },
  'narrative.discovery': { generator: 'impact', bus: 'narrative', volume: .22, duration: .42, frequency: 64, endFrequency: 42 },
  'narrative.entity': { generator: 'tone', bus: 'narrative', volume: .13, duration: .16, frequency: 690, endFrequency: 735, type: 'square', filter: 1300 },
  'impact.low': { generator: 'impact', bus: 'impact', volume: .32, duration: .52, frequency: 54, endFrequency: 31 },
  'impact.glitch': { generator: 'noise', bus: 'impact', volume: .18, duration: .09, filterType: 'highpass', filter: 1300, q: .5, panVariation: .08 },
  'impact.blackout': { generator: 'impact', bus: 'impact', volume: .36, duration: .62, frequency: 48, endFrequency: 24 },
  'rare.crackle': { generator: 'noise', bus: 'ambience', volume: .055, duration: .055, filterType: 'highpass', filter: 2100, q: .8, panVariation: .42 },
  'rare.relay': { generator: 'relay', bus: 'ambience', volume: .07, duration: .11, variants: [{ frequency: 125 }, { frequency: 148 }], panVariation: .3 },
  'rare.fragment': { generator: 'tone', bus: 'signal', volume: .025, duration: .12, frequency: 610, endFrequency: 570, type: 'square', filter: 1050, panVariation: .35 },
  'rare.wood': { generator: 'impact', bus: 'ambience', volume: .026, duration: .09, frequency: 98, endFrequency: 72, panVariation: .65 },
  'rare.distant': { generator: 'noise', bus: 'ambience', volume: .018, duration: .3, filterType: 'bandpass', filter: 310, q: 1.3, panVariation: .7 },
  'morse.radio': { generator: 'morse', bus: 'signal', volume: .15, frequency: 510, type: 'square', filter: 920, q: 3.4, rateVariation: .008 }
});

export const AUDIO_ENVIRONMENTS = Object.freeze({
  computer: { bus: 'ambience', hum: [49.8, 99.6], noise: .0045, volume: .032, filter: 280 },
  system: { bus: 'ambience', hum: [49.8, 99.6], noise: .0045, volume: .032, filter: 280 },
  archive: { bus: 'ambience', hum: [42, 84], noise: .008, volume: .024, filter: 520 },
  device: { bus: 'device', hum: [59.7, 119.4], noise: .018, volume: .042, filter: 1100, whine: 11800 },
  phone: { bus: 'device', hum: [61], noise: .002, volume: .018, filter: 420 },
  forensic: { bus: 'ambience', hum: [54, 108], noise: .006, volume: .026, filter: 360 },
  reconstruction: { bus: 'ambience', hum: [36, 71.6, 143.2], noise: .005, volume: .026, filter: 240 },
  override: { bus: 'ambience', hum: [27.5], noise: .002, volume: .012, filter: 150 }
});
